au

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,7 +1,28 @@
 #!/usr/bin/env bash
 #1. Install nginx web server
+
 sudo apt-get -y update
-sudo apt-get -y install nginx
-ufw allow 'Nginx HTTP'
-sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
-sudo service nginx start
+
+if sudo apt-get -y install nginx; then
+    echo -e \
+"http {
+    root /var/www/school;
+    index index.html;
+    server {
+        listen 80;
+        location / {
+        }
+    }
+}
+events {
+}" > /etc/nginx/nginx.conf
+
+    mkdir -p /var/www/school
+
+    echo "Hello World!" > /var/www/school/index.html
+
+    sudo service nginx start
+else
+    echo "Failed to install Nginx."
+    exit 1
+fi
